### ISSUE TITLE
grid not working after upgrade to 0.9.0

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#525]
html - ` k-widget.two-way="grid"
                    view-model.ref="grid"
                    id="grid"
                    k-data-source.bind="additionalInfoDatasource"
                    k-pageable.bind="pageable"
                    k-sortable.bind="true"
                    k-selectable.bind="true"
                    k-navigatable.bind="true"
                    k-reorderable.bind="true"
                    k-scrollable.bind="{ virtual: true}">`

and the JS :
`this.grid.kWidget.setDataSource(this.additionalInfoDatasource);`

what i get is `this.grid.kWidget.setDataSource is not a function`

**Comment by JeroenVinke** [comment]
k-widget and view-model.ref both point to `grid`

**Comment by eliavmaman** [comment]
hey @JeroenVinke .. long time no see :)
ok... b4 upgrade to 0.9.0, what the i didnt needed the view-model.ref attr but after the upgrade the line
`this.grid` stopped work.
then , i added the view-model.ref . but now nothing works.
what to do?

**Comment by eliavmaman** [comment]
@JeroenVinke any idea mate?

**Comment by JeroenVinke** [comment]
Well you definitely can't use view-model.ref="grid" and k-widget.two-way="grid" because they need to point to two variables (grid and gridVM) for example. But without viewmodel ref, from which function are you using `grid` from attached or bind?

**Comment by shanonvl** [comment]
@eliavmaman 

1. Remove `view-model.ref`
2. Change:  `k-widget.two-way="grid"` to `k-widget.bind="grid"`   (unless you specifically want this to be a two-way binding?)

Now you should be able to access `this.grid.setDataSource` as long as your JS is executed *in or after* `attached` to ensure that the binding has been updated.   

I *think* that should work...

**Comment by JeroenVinke** [comment]
From what version did you update to 0.9.0?

**Comment by eliavmaman** [comment]
one sec i'm trying

**Comment by eliavmaman** [comment]
0.6.0

**Comment by JeroenVinke** [comment]
Thats pretty old, (is the comment mentioned [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/releases/tag/0.6.0) relevant to you? Also, the latest version of the bridge is 0.10.5, not 0.9.0, could you verify that you are on the latest now?

**Comment by eliavmaman** [comment]
@JeroenVinke 
i did `jspm update` and got 0.9.0. 
i'll try to update to 0.10.5 manually now.

@shanonvl .
i Changed: k-widget.two-way="grid" to k-widget.bind="grid". and still got the same error- `this.grid.kWidget.setDataSource is not a function`

**Comment by eliavmaman** [comment]
@shanonvl  also as u suggested i removed the view-model.ref

**Comment by eliavmaman** [comment]
@JeroenVinke and @shanonvl  i want to kiss you ... @JeroenVinke - just update to  0.10.5 and every thing went like butter.

**Comment by eliavmaman** [comment]
10xxxxx a lot

**Comment by JeroenVinke** [comment]
glad it works :+1: @shanonvl thanks for helping out :smile:
