### ISSUE TITLE
aurelia typescript skeleton installation problem

### ISSUE THREAD

**Issue by el95149** [aurelia-ui-toolkits/aurelia-kendoui-bridge#684]
Hello, using:
Aurelia framework 1.0.8
Aurelia Kendo UI bridge 1.0.1
Kendo UI 2016.3.1306

and following installations instructions as per: http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation

the application fails, when trying to display a simple Window component.  Here's the relevant .html file:

```<template>

  <require from="aurelia-kendoui-bridge/window/window"></require>
.......
  <div id="window" ak-window="k-width: 600px; k-title: About Alvar Aalto; k-visible.bind: false;" k-on-close.delegate="onClose()">
............
</div>
</template>
```

Chrome console output:

aurelia-logging-console.js:54 ERROR [app-router] Error: Error invoking Window. Check the inner error for details.
Inner Error:
Message: The kendo control 'kendoWindow' is not available. Did you load this control?
Inner Error Stack:
Error: The kendo control 'kendoWindow' is not available. Did you load this control?
    at WidgetBase.control (http://10.0.0.146:63343/aurora-portal/jspm_packages/npm/aurelia-kendoui-bridge@1.0.1/common/widget-base.js:57:15)
    at new Window (http://10.0.0.146:63343/aurora-portal/jspm_packages/npm/aurelia-kendoui-bridge@1.0.1/window/window.js:23:36)

**Comment by JeroenVinke** [comment]
Hey @el95149 

You will get this error when the kendo control has not been loaded. There are basically two things you need to load: the kendo control and the aurelia-kendoui-bridge wrapper. You have done the latter, but seemingly not the former.

Kendo can be loaded in two ways: via a `<script>` tag in index.html or via a module loader. Please take a look at [these instructions](https://aurelia-ui-toolkits.gitbooks.io/kendo-ui-sdk-installation/content/installation/installing_kendo.html) and pick which one you would like to use. Let me know if this does not resolve the error

**Comment by iainduff** [comment]
Hi @el95149, @JeroenVinke 

I got this error today after upgrading from 0.12.4 to 1.1.1. 
I'm using JSPM and the kendo bower endpoint.

All you have to do is add the following into your config.js file and it works fine.

meta: {
    "aurelia-kendoui-bridge": {
      "deps": [
        "kendo-ui"
      ]
    }
  }

**Comment by JeroenVinke** [comment]
@iainduff interesting, thanks for sharing 👍

**Comment by el95149** [comment]
Hi @iainduff 

Adding the deps section to config.js did the trick, it works perfectly now!

Thanks a lot.
